import { Injectable, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../../../common/prisma/prisma.service";
import PDFDocument from "pdfkit";

@Injectable()
export class ReportsService {
  constructor(private readonly prisma: PrismaService) {}

  async generateSettlementPdf(monthId: string): Promise<Buffer> {
    const month = await this.prisma.month.findUnique({
      where: { id: monthId },
      include: {
        mess: {
          include: {
            members: {
              include: {
                user: true,
              },
            },
          },
        },
        meals: {
          include: {
            member: true,
          },
        },
        costs: true,
        deposits: {
          include: {
            member: true,
          },
        },
        settlement: true,
      },
    });

    if (!month) {
      throw new NotFoundException("Month not found");
    }

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on("data", (buffer: Buffer) => buffers.push(buffer));
        doc.on("end", () => resolve(Buffer.concat(buffers)));
        doc.on("error", (err: Error) => reject(err));

        // Header
        doc.fontSize(25).text("Meso Settlement Report", { align: "center" });
        doc.moveDown();
        doc.fontSize(16).text(`Mess: ${month.mess.name}`);
        doc.text(`Month: ${month.name}`);
        doc.text(`Status: ${month.status}`);
        doc.moveDown();

        // Summary
        const settlement = month.settlement;
        if (settlement) {
          doc.fontSize(18).text("Monthly Summary", { underline: true });
          doc
            .fontSize(12)
            .text(`Total Meals: ${settlement.totalMeals || 0}`);
          doc.text(`Meal Rate: ${settlement.mealRate?.toFixed(2) || 0}`);
          doc.text(`Total Cost: ${settlement.totalCost?.toFixed(2) || 0}`);
          doc.text(
            `Total Deposit: ${settlement.totalDeposit?.toFixed(2) || 0}`,
          );
          doc.moveDown();
        }

        // Member Breakdown Table
        doc.fontSize(18).text("Member Breakdown", { underline: true });
        doc.moveDown();

        let memberBalances: any = {};
        const memberLookup = new Map(
          month.mess.members.map((member) => [
            member.userId,
            `${member.user.firstName} ${member.user.lastName}`.trim() || member.user.email,
          ]),
        );

        if (!settlement) {
          doc.fontSize(12).text("No settlement data found for this month.");
          doc.end();
          return;
        }

        if (settlement?.memberBalances) {
          try {
            memberBalances = typeof settlement.memberBalances === "string"
              ? JSON.parse(settlement.memberBalances)
              : settlement.memberBalances;
          } catch (e) {
            console.error("Failed to parse member balances", e);
          }
        }

        Object.keys(memberBalances).forEach((memberId) => {
          const data = memberBalances[memberId];
          if (!data) return;
          
          doc
            .fontSize(12)
            .text(`Member: ${memberLookup.get(memberId) || memberId}`);
          doc.text(`- Meals: ${data.meals || 0}`);
          doc.text(`- Cost: ${(data.cost || 0).toFixed(2)}`);
          doc.text(`- Deposit: ${(data.deposit || 0).toFixed(2)}`);
          doc.text(`- Balance: ${(data.balance || 0).toFixed(2)}`);
          doc.moveDown(0.5);
        });

        // Footer
        doc.fontSize(10).text("Generated by Meso Mess Manager", {
          align: "center",
          baseline: "bottom",
        });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
